# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{vogue}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Sean St. Quentin"]
  s.date = %q{2010-03-31}
  s.description = %q{Vogue is a handy Rails gem which gives you more mechanisms for reducing your view and controller code as much as possible. It acheives this by encouraging providing additional helper methods in FormBuilder for working with related data, and providing template inheritance. }
  s.email = %q{sean.stquentin@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.markdown"
  ]
  s.files = [
    "README.markdown",
     "Rakefile",
     "VERSION",
     "lib/vogue.rb",
     "lib/vogue/dropdowns.rb",
     "lib/vogue/form_builder.rb",
     "lib/vogue/helpers.rb",
     "lib/vogue/partial_locator.rb",
     "lib/vogue/resource_controller_extensions.rb",
     "lib/vogue/template_locator.rb",
     "test/README",
     "test/Rakefile",
     "test/app/controllers/application_controller.rb",
     "test/app/controllers/posts_controller.rb",
     "test/app/controllers/priorities_controller.rb",
     "test/app/helpers/application_helper.rb",
     "test/app/helpers/posts_helper.rb",
     "test/app/helpers/priorities_helper.rb",
     "test/app/models/post.rb",
     "test/app/models/priority.rb",
     "test/app/views/layouts/standard/_header.html.erb",
     "test/app/views/layouts/standard/_specific.html.erb",
     "test/app/views/layouts/standard/_sub_header.html.erb",
     "test/app/views/layouts/standard/new.html.erb",
     "test/app/views/posts/_form.html.erb",
     "test/app/views/posts/_specific.html.erb",
     "test/config/boot.rb",
     "test/config/database.yml",
     "test/config/environment.rb",
     "test/config/environments/development.rb",
     "test/config/environments/production.rb",
     "test/config/environments/test.rb",
     "test/config/initializers/backtrace_silencers.rb",
     "test/config/initializers/inflections.rb",
     "test/config/initializers/mime_types.rb",
     "test/config/initializers/new_rails_defaults.rb",
     "test/config/initializers/session_store.rb",
     "test/config/locales/en.yml",
     "test/config/routes.rb",
     "test/db/development.sqlite3",
     "test/db/migrate/20100330233049_create_posts.rb",
     "test/db/migrate/20100330233402_create_priorities.rb",
     "test/db/schema.rb",
     "test/db/seeds.rb",
     "test/db/test.sqlite3",
     "test/lib/dropdowns.rb",
     "test/log/development.log",
     "test/log/production.log",
     "test/log/server.log",
     "test/log/test.log",
     "test/public/404.html",
     "test/public/422.html",
     "test/public/500.html",
     "test/public/favicon.ico",
     "test/public/images/rails.png",
     "test/public/index.html",
     "test/public/javascripts/application.js",
     "test/public/javascripts/controls.js",
     "test/public/javascripts/dragdrop.js",
     "test/public/javascripts/effects.js",
     "test/public/javascripts/prototype.js",
     "test/public/robots.txt",
     "test/script/about",
     "test/script/console",
     "test/script/dbconsole",
     "test/script/destroy",
     "test/script/generate",
     "test/script/performance/benchmarker",
     "test/script/performance/profiler",
     "test/script/plugin",
     "test/script/runner",
     "test/script/server",
     "test/test/blueprint.rb",
     "test/test/fixtures/posts.yml",
     "test/test/fixtures/priorities.yml",
     "test/test/functional/posts_controller_test.rb",
     "test/test/functional/priorities_controller_test.rb",
     "test/test/performance/browsing_test.rb",
     "test/test/test_helper.rb",
     "test/test/unit/form_builder_test.rb",
     "test/test/unit/helpers/posts_helper_test.rb",
     "test/test/unit/helpers/priorities_helper_test.rb",
     "test/test/unit/post_test.rb",
     "test/test/unit/priority_test.rb"
  ]
  s.homepage = %q{http://github.com/elseano/vogue}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Rails view inheritance, and handy form builder extensions.}
  s.test_files = [
    "test/app/controllers/application_controller.rb",
     "test/app/controllers/posts_controller.rb",
     "test/app/controllers/priorities_controller.rb",
     "test/app/helpers/application_helper.rb",
     "test/app/helpers/posts_helper.rb",
     "test/app/helpers/priorities_helper.rb",
     "test/app/models/post.rb",
     "test/app/models/priority.rb",
     "test/config/boot.rb",
     "test/config/environment.rb",
     "test/config/environments/development.rb",
     "test/config/environments/production.rb",
     "test/config/environments/test.rb",
     "test/config/initializers/backtrace_silencers.rb",
     "test/config/initializers/inflections.rb",
     "test/config/initializers/mime_types.rb",
     "test/config/initializers/new_rails_defaults.rb",
     "test/config/initializers/session_store.rb",
     "test/config/routes.rb",
     "test/db/migrate/20100330233049_create_posts.rb",
     "test/db/migrate/20100330233402_create_priorities.rb",
     "test/db/schema.rb",
     "test/db/seeds.rb",
     "test/lib/dropdowns.rb",
     "test/test/blueprint.rb",
     "test/test/functional/posts_controller_test.rb",
     "test/test/functional/priorities_controller_test.rb",
     "test/test/performance/browsing_test.rb",
     "test/test/test_helper.rb",
     "test/test/unit/form_builder_test.rb",
     "test/test/unit/helpers/posts_helper_test.rb",
     "test/test/unit/helpers/priorities_helper_test.rb",
     "test/test/unit/post_test.rb",
     "test/test/unit/priority_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<machinist>, [">= 0"])
    else
      s.add_dependency(%q<machinist>, [">= 0"])
    end
  else
    s.add_dependency(%q<machinist>, [">= 0"])
  end
end

